/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'primary-container': '#1a1c20',
        'on-primary': '#ffffff',
        'on-primary-container': '#828489',
        'primary-fixed': '#e2e2e8',
        'primary-fixed-dim': '#c6c6cc',
        'on-primary-fixed': '#1a1c20',
        'on-primary-fixed-variant': '#45474b',
        'inverse-primary': '#c6c6cc',

        secondary: '#1c3fe7',
        'secondary-container': '#405cff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#f5f3ff',
        'secondary-fixed': '#dee0ff',
        'secondary-fixed-dim': '#bbc3ff',
        'on-secondary-fixed': '#000f5d',
        'on-secondary-fixed-variant': '#002ccd',

        tertiary: '#000000',
        'tertiary-container': '#181c22',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#80848c',
        'tertiary-fixed': '#dfe2eb',
        'tertiary-fixed-dim': '#c3c6cf',
        'on-tertiary-fixed': '#181c22',
        'on-tertiary-fixed-variant': '#43474e',

        background: '#f7f9ff',
        surface: '#f7f9ff',
        'surface-dim': '#d7dae0',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4fa',
        'surface-container': '#eaeef4',
        'surface-container-high': '#e5e8ef',
        'surface-container-highest': '#dfe3e9',
        'surface-variant': '#dfe3e9',
        'surface-tint': '#5d5e63',

        'on-background': '#181c21',
        'on-surface': '#181c21',
        'on-surface-variant': '#45474b',
        'inverse-surface': '#2c3136',
        'inverse-on-surface': '#edf1f7',

        outline: '#76777b',
        'outline-variant': '#c6c6cb',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '5.5rem',
        gutter: '1.5rem',
        margin: '1.5rem',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
        display: ['var(--font-inter)', 'sans-serif'],
        'headline-lg': ['var(--font-inter)', 'sans-serif'],
        'headline-sm': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'sans-serif'],
        'mono-tag': ['var(--font-jetbrains-mono)', 'monospace'],
        'mono-counter': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      fontSize: {
        display: ['54px', { lineHeight: '1.08', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-mobile': ['38px', { lineHeight: '1.12', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '1.3', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.55', letterSpacing: '-0.005em', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'mono-tag': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-counter': ['12px', { lineHeight: '1', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
